version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load sensitive environment variables from .env file
    volumes:
      - .:/app  # Optional, for development purposes
    depends_on:
      - firestore_emulator

  firestore_emulator:
    image: "google/cloud-sdk:latest"
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8080:8080"
    env_file:
      - .env
