services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # Use the .env file in the current directory
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore_emulator:8080
    volumes:
      - .:/app  # For development only
      - ./logs:/app/logs  # Map the logs directory for centralized logging
    depends_on:
      - firestore_emulator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  firestore_emulator:
    build:
      context: .
      dockerfile: ./Dockerfile.firestore
    ports:
      - "8080:8080"
    env_file:
      - .env  # Use the .env file in the current directory
    volumes:
      - ./logs:/app/logs  # Optional: Map logs directory for the emulator if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
